import type { Constitution, Severity } from "@guardrail/core";

const SEVERITY_ORDER: Severity[] = ["critical", "error", "warning"];

export const GENERATED_NOTICE =
  "> Generated by `guardrail sync` from `.guardrail/constitution.md`. Do not edit this file directly — edit the constitution and re-run `guardrail sync`.";

/** Renders the constitution's rules, grouped by severity, as a Markdown list. Shared by every adapter. */
export function renderRulesList(constitution: Constitution): string {
  if (constitution.rules.length === 0) {
    return (
      "_No structured rules are enforced yet — this constitution is prose-only. " +
      "Run `guardrail init` or hand-write rules in `.guardrail/constitution.md` to enable enforcement._"
    );
  }

  const lines: string[] = [];
  for (const severity of SEVERITY_ORDER) {
    const rules = constitution.rules.filter((r) => r.severity === severity);
    if (rules.length === 0) continue;
    lines.push(`**${severity}**`);
    for (const rule of rules) {
      lines.push(`- \`${rule.id}\` (${rule.enforcement.type}) — ${rule.description}`);
    }
    lines.push("");
  }
  return lines.join("\n").trim();
}

/**
 * The shared template every "AI agent instructions" adapter (CLAUDE.md,
 * AGENTS.md, Copilot) renders from. These three files serve the same
 * purpose — telling a coding agent the project's architecture and the
 * rules that will be checked — so they intentionally share one template
 * rather than duplicating it three times.
 */
export function renderAgentMarkdown(constitution: Constitution, prose: string): string {
  return (
    [
      `# ${constitution.project.name}`,
      "",
      GENERATED_NOTICE,
      "",
      "## Architecture & conventions",
      "",
      prose.trim() || "_No additional architecture notes were provided._",
      "",
      "## Enforced rules",
      "",
      "These rules are checked deterministically by `guardrail check` — zero LLM calls, " +
        "zero network access. A violation of any `error`/`critical` rule fails CI.",
      "",
      renderRulesList(constitution),
      "",
    ].join("\n") + "\n"
  );
}
